spring:
  datasource:
  ##    LOCAL MYSQL
#      url: jdbc:mysql://localhost:3306/abclinic
#      username: root
#      password: 12345678

  ##    REMOTE MYSQL
      url: jdbc:mysql://remotemysql.com:3306/LQmSwtESHO
      username: LQmSwtESHO
      password: bsTH8SwIgY

  ##    REMOTE MYSQL
#        url: jdbc:mysql://remotemysql.com:3306/Cm2YXPzx0c
#        username: Cm2YXPzx0c
#        password: MknGXm8CTR

  ##    CLOUD SQL
#    url: jdbc:mysql://35.240.198.227:3306/abclinic
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  cloud:
#    gcp:
#      sql:
#        instance-connection-name: stoked-capsule-281607:asia-southeast1:abclinic-db
#        database-name: abclinic
#      firestore:
#        enabled: false
#    appId: stoked-capsule-281607
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db-changelog.xml
    drop-first: false
  servlet:
    ## MULTIPART (MultipartProperties)
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
  profiles:
    active: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
server:
  port: 8109
  servlet:
    context-path: /api
logging:
  level:
    org:
      hibernate:
        #        type.descriptor.sql.BasicBinder: trace
        SQL: debug
jwt:
  secret: abclinic-sec
  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: src/main/resources/uploads/
firebase:
  config-dir: abclinic-noti-firebase-adminsdk-9vf2a-3719016ef8.json