spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/LQmSwtESHO
    username: LQmSwtESHO
    password: EqtgG6sTqN
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db-changelog.xml
    drop-first: false
  servlet:
    ## MULTIPART (MultipartProperties)
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
server:
  port: 8109
  servlet:
    context-path: /api
  forward-headers-strategy: framework
logging:
  level:
    org:
      hibernate:
        SQL: debug
jwt:
  secret: abclinic-sec
app:
  firebase:
    configuration-file: D:/keen-optics-259713-firebase-adminsdk-9lt2z-9c1c0ada03.json
  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: src/main/resources/uploads/
