spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abclinic
    username: root
    password: 12345678
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/db-changelog.xml
    drop-first: true
server:
  port: 8109
